реализован интерфейс model
craftyard/command pull request #8
Opened 2024-02-16 12:57 UTC by FredSteady23

2024-02-21 07:24 UTC, NurGeo requested changes

2024-02-21 07:24 UTC, NurGeo commented on package.json
> +    "typeorm": "^0.3.20"
1. Для чего установлен sqlite3?
2. Для чего установлены два пакета: `"@nestjs/typeorm"`, `"typeorm"`

2024-02-21 07:24 UTC, NurGeo commented on src/app.module.ts
> +  )],
Для чего это? что она делает?

2024-02-21 07:24 UTC, NurGeo commented on src/app.module.ts
> +  )],
@xHetso а для чего у нас добавлен AppModule?

2024-02-21 07:24 UTC, NurGeo commented on src/model/model.entity.ts
все файлы непосредственно связанные с репозиторием спрятать в папку `repositories/model/`

2024-02-21 07:24 UTC, NurGeo commented on src/model/model.entity.ts
> +export class Model {
Назови ее `ModelEntity`

2024-02-21 07:24 UTC, NurGeo commented on src/model/model.repo.ts
> +    }
как дойдешь до этого коммента, запусти обсуждение в команде

2024-02-21 07:24 UTC, NurGeo commented on src/model/model.repo.ts
> +}
а где тесты???

2024-02-27 09:20 UTC, xHetso approved these changes

2024-03-12 11:59 UTC, merged